name: soul
on:
  push:
  pull_request:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
              21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
              31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
              41, 42, 43, 44, 45]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Compile soul.c
      run: chmod +x *
    - name: Run soul.py
      run: python3 soul.py
